-- ===========================================================================
-- iPropy CRM — 046: the blog and the daily SEO audit are gone
--
-- Neither was ever used. The blog module itself went in migration 030; what
-- survived was residue — two picklists nothing reads, and a `PUBLISHED` SQL
-- fragment in the public API that no query referenced. The audit was a daily
-- job that fetched the live website, scored it for SEO/AEO/GEO and stored the
-- findings for a trend line nobody opened.
--
-- The website is unaffected. Its titles, meta descriptions, canonicals, JSON-LD
-- and sitemap are generated by the Next.js app itself; this only removed the
-- thing that graded them afterwards.
--
-- Settings are deleted too, not just the table. `seo.site_url` left behind
-- would be a live-looking configuration field for a feature that no longer
-- exists, which is worse than no field at all.
-- ===========================================================================

DROP TABLE IF EXISTS ipy_seo_audit;

-- Belt and braces: 030 removed the module, but a database provisioned from an
-- older snapshot can still be carrying the payload table.
DROP TABLE IF EXISTS ipy_e_blog_posts;

DELETE FROM ipy_setting WHERE key IN ('seo.site_url', 'seo.audit_enabled');

-- Values cascade from ipy_picklist, so the parent row is enough.
DELETE FROM ipy_picklist WHERE name IN ('blog_status', 'blog_category');
